service: AWSSelfLearning

provider:
  name: aws
  runtime: java8
  region: ap-southeast-2
  versionFunctions: false
  profile: tw-aws-beach

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - s3:PutObject
        - s3:GetObject
        - sns:Publish
        - logs:*
      Resource: "*"

package:
  artifact: build/libs/hello-cloudFormation-1.0-SNAPSHOT.jar

functions:
  index:
    handler: lambda.backoffice
    events:
      - http:
          path: hello
          method: post
          cors: true

  Lambda1New:
    handler: lambda.Lambda1
    timeout: 900
    reservedConcurrency: 100
    events:
      - sns:
          arn: !Ref SuperTopicNew
          topicName: SuperTopicNew

  Lambda2New:
    handler: lambda.Lambda2
    timeout: 900
    reservedConcurrency: 100

  Lambda3New:
    handler: lambda.Lambda3
    timeout: 900
    reservedConcurrency: 100  #ReservedConcurrentExecutions(AWS)
    events:
      - schedule: cron(0 9 ? * 2#1 *) #cron(0/1 * ? * MON-FRI *)

resources:
  Resources:
    SuperTopicNew:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: MyCustomTopic

    S3FromLambda1Cache:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lambda1s3new

    S3FromLambda2Cache:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lambda2s3new

    OpsEventRule:
      Type: AWS::Events::Rule
      Properties:
        ScheduleExpression: cron(0 9 ? * 2#1 *) # Or EventPattern corn(0/1 * * * ? *)
        Description: EventRuleForSns
        State: ENABLED
        Targets:
          - Arn:
              Ref: SuperTopicNew
            Id: targetSnsV1

    EventTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sns:Publish
              Resource: '*'
        Topics:
          - !Ref SuperTopicNew